# Generated by Django 3.2 on 2021-04-23 06:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_ems', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='company_details',
            name='extra1',
            field=models.CharField(default='00000', max_length=5, validators=[django.core.validators.RegexValidator('^\\d{1,10}$')]),
        ),
    ]
