# Generated by Django 3.2 on 2021-04-27 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('site_ems', '0002_company_details_extra1'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company_details',
            name='extra1',
        ),
    ]
